Integrate wbs-precheck into wbs. Reindent lines

diff --git a/example/wbs b/example/wbs
--- a/example/wbs
+++ b/example/wbs
@@ -3,23 +3,23 @@
 source defaults.env
 
 if [[ -f ".env" ]]; then
-	source .env
+  source .env
 fi
 
 # === Flags
 for arg in "$@"; do
-		case $arg in
-				# ./wbs <command> --quiet, ./wbs <command> -q
-				# Quiets logging of Docker operations
-				--quiet|-q)
-					flag_quiet=true
-					;;
-				# ./wbs <start|stop> --reset
-				# Prompts user about resetting data before running start or stop
-				--reset)
-					flag_reset=true
-					;;
-		esac
+  case $arg in
+    # ./wbs <command> --quiet, ./wbs <command> -q
+    # Quiets logging of Docker operations
+    --quiet|-q)
+      flag_quiet=true
+      ;;
+    # ./wbs <start|stop> --reset
+    # Prompts user about resetting data before running start or stop
+    --reset)
+      flag_reset=true
+      ;;
+  esac
 done
 
 # == Docker compose command setup
@@ -29,7 +29,7 @@ export WBS_COMPOSE="docker compose \
 --profile nginx-proxy"
 
 if [ "$flag_quiet" = true ]; then
-	WBS_COMPOSE="$WBS_COMPOSE --progress quiet"
+  WBS_COMPOSE="$WBS_COMPOSE --progress quiet"
 fi
 
 export WBS_COMPOSE_UP="$WBS_COMPOSE up -d --wait"
@@ -48,197 +48,219 @@ clreset=$(tput sgr0)
 
 # Default Ctrl-C handler
 function cancel {
-	stop
-	exit 1
+  stop
+  exit 1
 }
 
 # Is WBS already running?
 function running {
-	local is_running
-	is_running=$($WBS_COMPOSE ps --quiet)
-	if [ -n "$is_running" ]; then
-		return 0
-	else
-		return 1
-	fi
+  local is_running
+  is_running=$($WBS_COMPOSE ps --quiet)
+  if [ -n "$is_running" ]; then
+    return 0
+  else
+    return 1
+  fi
 }
 
 # Starts WBS, if already running prompts user if they would like to restart WBS
 function start {
-	if running; then
-		echo "${clgreen}Wikibase Suite (WBS) is currently running${clreset} "
-		echo
-		$WBS_COMPOSE ps --format "table {{.Service}}\t{{.Image}}\t{{.Status}}"
-	else
-		echo "${clwhite}Waiting for Wikibase Suite containers to start...${clreset} "
-		trap cancel SIGINT
-		$WBS_COMPOSE_UP
-		if ! [ "$flag_quiet" = "true " ]; then 
-			echo
-		fi
-		echo "${clgreen}READY${clreset}"
-	fi
-	echo
-	echo "${clblue}http://${WIKIBASE_HOST}${clwhite}"
-	echo "${clblue}http://${WDQS_FRONTEND_HOST}${clwhite}"
-	echo "${clblue}http://${QUICKSTATEMENTS_HOST}${clwhite}"
-	echo "$clreset"
-	echo "${clyellow}./wbs stop${clwhite}              Stop WBS"
-	echo "${clyellow}./wbs stop --reset${clwhite}      Stop WBS and optionally reset the data"
-	echo "${clyellow}./wbs reset${clwhite}             Stop WBS and optionally reset the data AND configuration"
-	echo "${clyellow}./wbs compose logs -f${clwhite}   Show and follow WBS logs"
-	echo "$clreset"
+  if running; then
+    echo "${clgreen}Wikibase Suite (WBS) is currently running${clreset} "
+    echo
+    $WBS_COMPOSE ps --format "table {{.Service}}\t{{.Image}}\t{{.Status}}"
+  else
+    echo "${clwhite}Waiting for Wikibase Suite containers to start...${clreset} "
+    trap cancel SIGINT
+    $WBS_COMPOSE_UP
+    if ! [ "$flag_quiet" = "true " ]; then 
+      echo
+    fi
+    echo "${clgreen}READY${clreset}"
+  fi
+  echo
+  echo "${clblue}http://${WIKIBASE_HOST}${clwhite}"
+  echo "${clblue}http://${WDQS_FRONTEND_HOST}${clwhite}"
+  echo "${clblue}http://${QUICKSTATEMENTS_HOST}${clwhite}"
+  echo "$clreset"
+  echo "${clyellow}./wbs stop${clwhite}              Stop WBS"
+  echo "${clyellow}./wbs stop --reset${clwhite}      Stop WBS and optionally reset the data"
+  echo "${clyellow}./wbs reset${clwhite}             Stop WBS and optionally reset the data AND configuration"
+  echo "${clyellow}./wbs compose logs -f${clwhite}   Show and follow WBS logs"
+  echo "$clreset"
 }
 
 # Stops WBS and removes docker volumes, prompts user for confirmation
 function reset_data {
-	read -p "${clred}Erase Wikibase Suite data for all services? This can't be undone. (No) ${clreset}" -n 1 -r
-	echo
-	if [[ $REPLY =~ ^[Yy]$ ]]; then
-		echo "${clwhite}Stopping Wikibase Suite and erasing data...${clreset} "
-		$WBS_COMPOSE_DOWN_VOLUMES
-		echo "${clblue}DONE${clreset}"
-	fi
+  read -p "${clred}Erase Wikibase Suite data for all services? This can't be undone. (No) ${clreset}" -n 1 -r
+  echo
+  if [[ $REPLY =~ ^[Yy]$ ]]; then
+    echo "${clwhite}Stopping Wikibase Suite and erasing data...${clreset} "
+    $WBS_COMPOSE_DOWN_VOLUMES
+    echo "${clblue}DONE${clreset}"
+  fi
+}
+
+function delete_and_backup_env {
+  if [[ -f ".env" ]]; then
+    mv .env .env.backup
+    echo "Current ${clblue}.env${clreset} moved to ${clblue}.env_backup${clreset}"
+  fi
 }
 
 # Set MW_SECRET_KEY to a unique value in .env
 function create_mw_secret_key {
-	local mw_secret_key
-	mw_secret_key=$(LC_ALL=C tr -dc 'A-Za-z0-9@#%^+_-' </dev/urandom | head -c 64 ; echo '')
-	sed -i~ "/^MW_SECRET_KEY=/s/=.*/=${mw_secret_key}/" .env
+  local mw_secret_key
+  mw_secret_key=$(LC_ALL=C tr -dc 'A-Za-z0-9@#%^+_-' </dev/urandom | head -c 64 ; echo '')
+  sed -i~ "/^MW_SECRET_KEY=/s/=.*/=${mw_secret_key}/" .env
 }
 
 function create_mw_admin_pass {
-	mw_admin_pass=$(LC_ALL=C tr -dc 'A-Za-z0-9@#%^+_-' </dev/urandom | head -c 12 ; echo '')
-	sed -i~ "/^MW_ADMIN_PASS=/s/=.*/=${mw_admin_pass}/" .env
+  mw_admin_pass=$(LC_ALL=C tr -dc 'A-Za-z0-9@#%^+_-' </dev/urandom | head -c 12 ; echo '')
+  sed -i~ "/^MW_ADMIN_PASS=/s/=.*/=${mw_admin_pass}/" .env
 }
 
 function create_db_pass {
-	db_pass=$(LC_ALL=C tr -dc 'A-Za-z0-9@#%^+_-' </dev/urandom | head -c 12 ; echo '')
-	sed -i~ "/^DB_PASS=/s/=.*/=${db_pass}/" .env
+  db_pass=$(LC_ALL=C tr -dc 'A-Za-z0-9@#%^+_-' </dev/urandom | head -c 12 ; echo '')
+  sed -i~ "/^DB_PASS=/s/=.*/=${db_pass}/" .env
 }
 
 # Overwrites .env with a copy of template.env, prompts user for confirmation
 function create_env_from_template {
-	if [[ -f ".env" ]]; then
-		mv .env .env.backup
-		echo "Current ${clblue}.env${clreset} moved to ${clblue}.env_backup${clreset}"
-	fi
-	cp template.env .env
-	create_mw_secret_key
-	create_mw_admin_pass
-	create_db_pass
-	echo "A new default configuration has been copied from ${clblue}template.env${clreset} to ${clblue}.env${clreset}"
+  delete_and_backup_env
+  cp template.env .env
+  create_mw_secret_key
+  create_mw_admin_pass
+  create_db_pass
+  echo "A new default configuration has been copied from ${clblue}template.env${clreset} to ${clblue}.env${clreset}"
 }
 
 # Reset WBS configuration and data (prompts user)
 function reset {
-	reset_data
-	echo
-	read -p "${clred}Reset the configuration in .env back to the template? (No) ${clreset}" -n 1 -r
-	echo
-	if [[ $REPLY =~ ^[Yy]$ ]]; then
-		welcome_setup
-	fi
-	echo
+  reset_data
+  echo
+  read -p "${clred}Reset the configuration in .env back to the template? (No) ${clreset}" -n 1 -r
+  echo
+  if [[ $REPLY =~ ^[Yy]$ ]]; then
+    delete_and_backup_env
+  fi
+  echo
 }
 
 # Stops WBS
 function stop {
-	if [ "$flag_reset" = true ]; then
-		reset_data
-	else
-		if running ; then
-			trap "exit 1" SIGINT
-			echo "${clwhite}Stopping currently running Wikibase Suite... "
-			$WBS_COMPOSE_DOWN
-			if [ "$flag_quiet" = true ]; then 
-				echo "${clblue}DONE${clreset}"
-			fi
-			echo
-		fi
-	fi
+  if [ "$flag_reset" = true ]; then
+    reset_data
+  else
+    if running ; then
+      trap "exit 1" SIGINT
+      echo "${clwhite}Stopping currently running Wikibase Suite... "
+      $WBS_COMPOSE_DOWN
+      if [ "$flag_quiet" = true ]; then 
+        echo "${clblue}DONE${clreset}"
+      fi
+      echo
+    fi
+  fi
+}
+
+function run_precheck {
+  ./wbs-precheck
+  # Check if precheck failed
+  if [ $? -ne 0 ]; then
+  read -p "${clred}Do you want to ignore this and continue setting up WBS now anyway? (No):${clreset} " choice
+  case "$choice" in
+    y|Y )
+      echo
+      ;;
+    * )
+      echo "Setup aborted."
+      exit 1
+      ;;
+  esac
+  fi
 }
 
 # Creates a new .env file and welcomes user with next steps
 function welcome_setup {
-	# Green text
-	echo "$clgreen"
-	echo "Welcome to the Wikibase Suite (WBS)"
-	echo "$clwhite"
+  # Green text
+  echo "$clgreen"
+  echo "Welcome to the Wikibase Suite (WBS)"
+  echo "$clwhite"
 
-	create_env_from_template
-	source .env
+  run_precheck
+  create_env_from_template
+  source .env
 
-	echo
-	echo "Next steps:"
-	echo
-	echo "1. Open the ${clblue}.env${clwhite} file to set your email address and confirm the configuration"
-	echo
-	if [[ "$1" = "start" ]]; then
-		echo "2. Run ${clblue}./wbs start${clwhite} again to start WBS"
-	else
-		echo "2. Run ${clblue}./wbs start${clwhite} to start WBS"
-	fi
-	echo
-	echo "3. Once you see ${clgreen}READY${clwhite} navigate to ${clblue}http://${WIKIBASE_HOST}${clwhite} and begin testing!"
-	# Yellow text
-	echo "$clyellow"
-	echo "DISCLAIMER: This WBS configuration is an example of how to use the WBS Docker images together,"
-	echo "but not production-ready."
-	echo "$clreset"
+  echo
+  echo "Next steps:"
+  echo
+  echo "1. Open the ${clblue}.env${clwhite} file to set your email address and confirm the configuration"
+  echo
+  if [[ "$1" = "start" ]]; then
+    echo "2. Run ${clblue}./wbs start${clwhite} again to start WBS"
+  else
+    echo "2. Run ${clblue}./wbs start${clwhite} to start WBS"
+  fi
+  echo
+  echo "3. Once you see ${clgreen}READY${clwhite} navigate to ${clblue}http://${WIKIBASE_HOST}${clwhite} and begin testing!"
+  # Yellow text
+  echo "$clyellow"
+  echo "DISCLAIMER: This WBS configuration is an example of how to use the WBS Docker"
+  echo "images together, but not production-ready."
+  echo "$clreset"
 }
 
 # == Welcome and Setup - always runs when no `.env` file exists
 if ! [[ -f ".env" ]]; then
-	welcome_setup "$1"
-	exit 0
+  welcome_setup "$1"
+  exit 0
 fi
 
 echo
 
 # === Commands
 for arg in "$@"; do
-		case $arg in
-				# ./wbs reset
-				# Prompts user about resetting data AND configuration
-				reset)
-					reset
-					exit 0
-					;;
-				# ./wbs start
-				# Starts (or restarts if already running) all WBS services
-				# Accepts `--reset` flag e.g. `./wbs start --reset`
-				start)
-					start
-					exit 0
-					;;
-				# ./wbs stop
-				# Stops all running WBS services
-				# Accepts `--reset` flag e.g. `./wbs stop --reset`
-				stop)
-					stop
-					exit 0
-					;;
-				# ./wbs compose <compose-options-and-command>
-				# Runs `docker compose` with the WBS setup appending any arguments
-				# e.g. `./wbs compose logs`, `./wbs compose ps`, etc
-				compose)
-					$WBS_COMPOSE "${@:2}"
-					exit 0
-					;;
-				# ./wbs bash <service-name>
-				# Opens a bash shell on the specified WBS container
-				# e.g. `./wbs bash wikibase`
-				bash)
-					$WBS_COMPOSE exec "$2" bash
-					exit 0
-					;;
-				*)
-					echo "Unknown argument: $arg" > /dev/stderr
-					exit 1
-					;;
-		esac
+  case $arg in
+    # ./wbs reset
+    # Prompts user about resetting data AND configuration
+    reset)
+      reset
+      exit 0
+      ;;
+    # ./wbs start
+    # Starts (or restarts if already running) all WBS services
+    # Accepts `--reset` flag e.g. `./wbs start --reset`
+    start)
+      start
+      exit 0
+      ;;
+    # ./wbs stop
+    # Stops all running WBS services
+    # Accepts `--reset` flag e.g. `./wbs stop --reset`
+    stop)
+      stop
+      exit 0
+      ;;
+    # ./wbs compose <compose-options-and-command>
+    # Runs `docker compose` with the WBS setup appending any arguments
+    # e.g. `./wbs compose logs`, `./wbs compose ps`, etc
+    compose)
+      $WBS_COMPOSE "${@:2}"
+      exit 0
+      ;;
+    # ./wbs bash <service-name>
+    # Opens a bash shell on the specified WBS container
+    # e.g. `./wbs bash wikibase`
+    bash)
+      $WBS_COMPOSE exec "$2" bash
+      exit 0
+      ;;
+    *)
+      echo "Unknown argument: $arg" > /dev/stderr
+      exit 1
+      ;;
+  esac
 done
 
 # default command
diff --git a/example/wbs-precheck b/example/wbs-precheck
--- a/example/wbs-precheck
+++ b/example/wbs-precheck
@@ -6,64 +6,65 @@ MIN_DOCKER_COMPOSE_VERSION="2.10"
 
 source template.env
 
+# Adds result for final report
+add_result() {
+  if ! [ "$1" -eq 0 ]; then
+    RESULTS+="❌ FAIL: $2"$'\n'
+  fi
+}
+
 # Function to compare version numbers using semver
 semver_compare() {
-    local version1 version2
+  local version1 version2
 
-    # Use awk to extract numeric parts of the version string
-    version1=$(echo "$1" | awk -F. '{print $1*10000+$2*100+$3}')
-    version2=$(echo "$2" | awk -F. '{print $1*10000+$2*100+$3}')
+  # Use awk to extract numeric parts of the version string
+  version1=$(echo "$1" | awk -F. '{print $1*10000+$2*100+$3}')
+  version2=$(echo "$2" | awk -F. '{print $1*10000+$2*100+$3}')
 
-    if [ "$version1" -eq "$version2" ]; then
-        return 0
-    elif [ "$version1" -gt "$version2" ]; then
-        return 1
-    else
-        return 2
-    fi
+  if [ "$version1" -eq "$version2" ]; then
+    return 0
+  elif [ "$version1" -gt "$version2" ]; then
+    return 1
+  else
+    return 2
+  fi
 }
 
 # Function to check software version
 check_version() {
-    software="$1"
-    min_version="$2"
-    command_name="$3"
-    
-    if [ "$command_name" == "docker compose" ]; then
-        version="$($command_name version --short)"
-    else
-        version="$("$command_name" --version | awk '{print $3}' | sed 's/,//' | awk -F. '{print $1"."$2"."$3}')"
-    fi
+  software="$1"
+  min_version="$2"
+  command_name="$3"
+  
+  if [ "$command_name" == "docker compose" ]; then
+    version="$($command_name version --short)"
+  else
+    version="$("$command_name" --version | awk '{print $3}' | sed 's/,//' | awk -F. '{print $1"."$2"."$3}')"
+  fi
 
-    # Check if the version is numeric
-    if [ -n "$version" ] && [[ "$version" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
-        semver_compare "$version" "$min_version"
-        result=$?
+  # Check if the version is numeric
+  if [ -n "$version" ] && [[ "$version" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+    semver_compare "$version" "$min_version"
+    result=$?
 
-        if [ "$result" -eq 0 ]; then
-            RESULTS+="✅ PASS: $software version is $version (equal to $min_version)"$'\n'
-        elif [ "$result" -eq 2 ]; then
-            RESULTS+="❌ FAIL: $software version is $version (below $min_version)"$'\n'
-        else
-            RESULTS+="✅ PASS: $software version is $version (above $min_version)"$'\n'
-        fi
-    else
-        RESULTS+="❌ FAIL: Unable to determine $software version or not installed"$'\n'
+    if [ "$result" -eq 2 ]; then
+      add_result 1 "$software version is $version (below $min_version)"
     fi
+  else
+    add_result 1 "Unable to determine $software version or not installed"
+  fi
 }
 
 # Function to check if the domain name can be resolved
 check_domain_resolution() {
-    domain="$1"
-    
-    # Use dig to obtain the resolved IP address
-    ip_address=$(dig +short "$domain")
+  domain="$1"
+  
+  # Use dig to obtain the resolved IP address
+  ip_address=$(dig +short "$domain")
 
-    if [ -n "$ip_address" ]; then
-        RESULTS+="✅ PASS: $domain found (resolves to $ip_address)"$'\n'
-    else
-        RESULTS+="❌ FAIL: $domain not found"$'\n'
-    fi
+  if [ -z "$ip_address" ]; then
+    add_result 1 "$domain not found"$'\n'
+  fi
 }
 
 # Store PASS/FAIL results
@@ -77,18 +78,19 @@ check_version "Docker Compose" "$MIN_DOCKER_COMPOSE_VERSION" "docker compose"
 check_domain_resolution "$WIKIBASE_HOST"
 
 # Check architecture
-if [ "$(uname -m)" == "x86_64" ] || [ "$(uname -m)" == "amd64" ]; then
-    RESULTS+="✅ PASS: Computer architecture is AMD64"$'\n'
-else
-    RESULTS+="❌ FAIL: Computer architecture is not AMD64 (ARM not currently supported)"$'\n'
+if ! [ "$(uname -m)" == "x86_64" ] || [ "$(uname -m)" == "amd64" ]; then
+  add_result 1 "Computer architecture is not AMD64 (ARM not currently supported)"
 fi
 
-# Print results
-echo "$RESULTS"
+function print_report() {
+  if grep -q "FAIL" <<< "$RESULTS"; then
+    echo "Precheck failed with the followiing issue/s:"
+    echo
+    echo "$RESULTS"
+    echo "Please review the documentation to resolve the above issues."
+    echo
+    return 1
+  fi
+}
 
-# Check if all requirements are met
-if grep -q "FAIL" <<< "$RESULTS"; then
-    echo "Please review above and WBS documentation to resolve issues."
-else
-    echo "✅ All ready to run WBS! Run \`./wbs\` 🚀"
-fi
+print_report
