In progrees PNPM / ts / eslint config update

diff --git a/nx b/nx
--- a/nx
+++ b/nx
@@ -3,24 +3,25 @@
 # Ensure the script exits on error
 set -e
 
+# Get the current working directory
+WORKDIR=$(pwd)
 IMAGE_NAME="nx-runner:latest"
-
-echo "Current CI VALUE: $CI"
 
 # Check if we're in a CI environment
 if [ "$CI" = "true" ]; then
-  npm ci
-  npx nx "$@"
+  echo "Running NX directly (CI is \"true\")"
+  corepack enable
+  pnpm install --frozen-lockfile
+  pnpm nx "$@"
 else
-  # Get the current working directory
-  WORKDIR=$(pwd)
-  if ! docker image inspect $IMAGE_NAME > /dev/null 2>&1; then
-    echo "Docker image $IMAGE_NAME not found. Building it..."
-    docker build -t $IMAGE_NAME .
-  fi
+  # if ! docker image inspect $IMAGE_NAME > /dev/null 2>&1; then
+  #   echo "Docker image $IMAGE_NAME not found. Building it..."
+  #   docker build -t $IMAGE_NAME . --no-cache
+  # fi
   # Run the Nx command inside the Docker container
+  docker build --quiet -t $IMAGE_NAME . > /dev/null
   docker run --rm -it \
-    -v "$WORKDIR:/workspace" \
+    -v "$WORKDIR":/workspace \
     -v /var/run/docker.sock:/var/run/docker.sock \
     -w /workspace \
     $IMAGE_NAME "$@"
