feat: METADATA_CALLBACK initially empty

diff --git a/deploy/docker-compose.yml b/deploy/docker-compose.yml
--- a/deploy/docker-compose.yml
+++ b/deploy/docker-compose.yml
@@ -11,7 +11,14 @@ services:
       - bash
       - -c
       - |
-        if [ -v METADATA_CALLBACK  ] && [ "$METADATA_CALLBACK" = "true" ]; then
+        if ! [ -v METADATA_CALLBACK  ] || ! [ -n "$METADATA_CALLBACK" ]; then
+          echo "*** ERROR ***"
+          echo "METADATA_CALLBACK not configured. Please set it in your .env file."
+          echo "Find more information about METADATA_CALLBACK in ./template.env and on "
+          echo "https://github.com/wmde/wikibase-release-pipeline/blob/main/deploy/README.md"
+          echo "Exiting Wikibase container now."
+          exit 1
+        elif [ -v METADATA_CALLBACK  ] && [ "$METADATA_CALLBACK" = "true" ]; then
           bash /callback.sh
         fi
         exec bash /entrypoint.sh
