feat: tag

diff --git a/.github/workflows/build_test_publish_release.yml b/.github/workflows/build_test_publish_release.yml
--- a/.github/workflows/build_test_publish_release.yml
+++ b/.github/workflows/build_test_publish_release.yml
@@ -1,17 +1,54 @@
-name: 📦🛸 Build Test and Publish Release
+name: 📦🛸 Build Test Tag and Publish Release
 
 on:
   push:
     branches:
       - "mw-*"
 
+permissions:
+  contents: write
+
 jobs:
   _:
     uses: ./.github/workflows/_build_test.yml
 
+  tag-release:
+    needs: _
+    runs-on: ubuntu-latest
+
+    steps:
+      - uses: actions/checkout@v4
+
+      - run: |
+          set -e # abort on error
+          set -x # show commands
+
+          set -o allexport
+          source ./varibales.env
+
+          git tag "$WMDE_RELEASE_VERSION"
+
+
+          git config --global user.name 'wikibase suite github actions bot'
+          git config --global user.email 'wikibase-suite-github-actions-bot@users.noreply.github.com'
+
+          if git tag "$WMDE_RELEASE_VERSION"; then
+            git push --tags origin "$WMDE_RELEASE_VERSION"
+          else
+            echo "*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***"
+            echo "Cannot tag $WMDE_RELEASE_VERSION, Most probably this tag is already given to another commit."
+            echo "Make sure to update the WMDE_RELEASE_VERSION varibable in variables.env to publish a new release."
+            echo "*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***"
+          fi
+
   publish-dockerhub:
+    needs: 
+      - _
+      - tag-release
+
     runs-on: ubuntu-latest
     timeout-minutes: 30
+
 
     strategy:
       fail-fast: false
